$(function () {
	//Click por fuera para esconder Menú
	$("body").click(function () {
		$("#menuShow").removeClass("header-nav-list--show");
		$("#productsList").removeClass("header-nav-list-item-subnav-show");
		$("#companyList").removeClass("header-nav-list-item-subnav2-show");
	});
	//Mostrar el menú al click
	$("#buttonNav").click(function (event) {
		event.stopPropagation();
		$("#menuShow").toggleClass("header-nav-list--show");
		$("#productsList").removeClass("header-nav-list-item-subnav-show");
		$("#companyList").removeClass("header-nav-list-item-subnav2-show");
		//$('img', this).toggle(); Cambia el botón del menú al click
	});
	//Mostrar el submenú al click
	$("#productNav").click(function (event) {
		event.stopPropagation();
		$("#productsList").toggleClass("header-nav-list-item-subnav-show");
	});
	//Mostrar el submenú al click
	$("#aboutNav").click(function (event) {
		event.stopPropagation();
		$("#companyList").toggleClass("header-nav-list-item-subnav2-show");
	});
	//Realizar la busqueda y colocar cursor al click en la lupa
	$('#findBox')
	.find('form')
	.submit(function(ev) {
		ev.preventDefault();
		var search = $(this)
		.find('input[type="text"]')
		.val();
		$('.header-interaction-mobile-choice-finder-box').focus();
	})
	//No mostrar lso botones de búsqueda ni de carro de compras
	$('.product-images-item-marketcar').css({
		display: 'none'
	});
	$('.category-images-item-marketcar').css({
		display: 'none'
	});
	$('#findBox').css({
		display: 'none'
	});

	//Cambiar la disposición de las imágenes dependiendo del tamaño del dispositivo
	if($(window).width() > 550 && $(window).width() < 1200) {
		var width = $(window).width();
		$(window).resize(function() {
			if($(this).width() != width) {
				width = $(this).width();
				location.reload();
			}
		});	
	}
	//Cambiar la barra del menú con scroll dependiendo de la posición en Y
	if($(window).width() < 768) {
		$(window).scroll(function(event) {
		    var y = $(this).scrollTop();
		    if (y >= 140) {
		        $("#menuFixed").addClass('header-interaction-mobile--light');
		        $(".header-nav").addClass("fixed");
		        $("#menuButton").attr("src", "img/menu-.png");
		        $("#menuButton1").attr("src", "img/menu1-.png");
		        $("#finder").attr("src", "img/lupa-.png");
		    
		    } 
		    else {
		        $("#menuFixed").removeClass('header-interaction-mobile--light');
		        $(".header-nav").removeClass("fixed");
		        $("#menuButton").attr("src", "img/menu+.png");
		        $("#menuButton1").attr("src", "img/menu1+.png");
		        $("#finder").attr("src", "img/lupa+.png");
				}
			if (y >= 140) {
				$('#closeButton').css({
					top: '60px'
				});
			}
			else {
				$('#closeButton').css({
					top: '0px'
				});	
			}
		});
	}
	//Quitar el loader cuando es un dispositivo grande
	if($(window).width() > 768) {
		$(".content").find(".loader").remove();
	}
	//Activar el Lazy Loader
	$(function() {
    	$("img").lazyload({placeholder : "img/grey.gif", threshold : 100, effect : "fadeIn"});
	});
	//Script de Google Analytics
	// (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	// 		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	// 		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	// 		})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	// 		ga('create', 'UA-79744708-1', 'auto');
	// 		ga('send', 'pageview');
	//Cambiar imágenes de home al hacer hover
	$('#man-img').hover(function() {
		/* Stuff to do when the mouse enters the element */
		$('#man-img').find('source').attr('srcset', 'img/hombres.jpg');
	}, function() {
		/* Stuff to do when the mouse leaves the element */
		$('#man-img').find('source').attr('srcset', 'img/hombre-mobile.jpg');
	});
	$('#woman-img').hover(function() {
		/* Stuff to do when the mouse enters the element */
		$('#woman-img').find('source').attr('srcset', 'img/mujeres.jpg');
	}, function() {
		/* Stuff to do when the mouse leaves the element */
		$('#woman-img').find('source').attr('srcset', 'img/mujer-mobile.jpg');
	});
	$('#accesories-img').hover(function() {
		/* Stuff to do when the mouse enters the element */
		$('#accesories-img').find('source').attr('srcset', 'img/bolsos.jpg');
	}, function() {
		/* Stuff to do when the mouse leaves the element */
		$('#accesories-img').find('source').attr('srcset', 'img/bolsos-mobile.jpg');
	});

	$('#1012').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/1012-1.jpg'); $('#tabletView').attr('srcset', 'img/1012-1.jpg'); $('#mobileView').attr('src', 'img/1012-1.jpg'); $('#desktopView2').attr('srcset', 'img/1012-2.jpg'); $('#tabletView2').attr('srcset', 'img/1012-2.jpg'); $('#mobileView2').attr('src', 'img/1012-2.jpg'); $('#desktopView3').attr('srcset', 'img/1012-3.jpg'); $('#tabletView3').attr('srcset', 'img/1012-3.jpg'); $('#mobileView3').attr('src', 'img/1012-3.jpg'); $('.product-images-item-info-material').text('Material: Charol'); $('.product-images-item-info-price').text('Tacón 1012SAL'); $('.product-images-item-info-color').text('Colores: Negro, Café, Negro, Beige, Palorosa, Salmón, Rojo, Azul, Vinotinto, Verde.');$('#selector1').click();});
	$('#030').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/030-1.jpg'); $('#tabletView').attr('srcset', 'img/030-1.jpg'); $('#mobileView').attr('src', 'img/030-1.jpg'); $('#desktopView2').attr('srcset', 'img/030-2.jpg'); $('#tabletView2').attr('srcset', 'img/030-2.jpg'); $('#mobileView2').attr('src', 'img/030-2.jpg'); $('#desktopView3').attr('srcset', 'img/030-3.jpg'); $('#tabletView3').attr('srcset', 'img/030-3.jpg'); $('#mobileView3').attr('src', 'img/030-3.jpg'); $('.product-images-item-info-material').text('Material: Charol'); $('.product-images-item-info-price').text('Tacón 030PR'); $('.product-images-item-info-color').text('Colores: Negro, Café, Negro, Beige, Palorosa, Salmón, Rojo, Azul, Vinotinto, Verde.');$('#selector1').click();});
	$('#027').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/027-1.jpg'); $('#tabletView').attr('srcset', 'img/027-1.jpg'); $('#mobileView').attr('src', 'img/027-1.jpg'); $('#desktopView2').attr('srcset', 'img/027-2.jpg'); $('#tabletView2').attr('srcset', 'img/027-2.jpg'); $('#mobileView2').attr('src', 'img/027-2.jpg'); $('#desktopView3').attr('srcset', 'img/027.jpg'); $('#tabletView3').attr('srcset', 'img/027.jpg'); $('#mobileView3').attr('src', 'img/027.jpg'); $('.product-images-item-info-material').text('Material: Microfibra'); $('.product-images-item-info-price').text('Tacón 027RO'); $('.product-images-item-info-color').text('Colores: Negro, Beige, Café, Azul, Rojo, Gris.');$('#selector1').click();});
	$('#030P').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/030P-1.jpg'); $('#tabletView').attr('srcset', 'img/030P-1.jpg'); $('#mobileView').attr('src', 'img/030P-1.jpg'); $('#desktopView2').attr('srcset', 'img/030P-2.jpg'); $('#tabletView2').attr('srcset', 'img/030P-2.jpg'); $('#mobileView2').attr('src', 'img/030P-2.jpg'); $('#desktopView3').attr('srcset', 'img/030P.jpg'); $('#tabletView3').attr('srcset', 'img/030P.jpg'); $('#mobileView3').attr('src', 'img/030P.jpg'); $('.product-images-item-info-material').text('Material: Charol'); $('.product-images-item-info-price').text('Tacón 030PNE'); $('.product-images-item-info-color').text('Colores: Negro y Café.');$('#selector1').click();});
	$('#bal01').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal01-1.jpg'); $('#tabletView').attr('srcset', 'img/bal01-1.jpg'); $('#mobileView').attr('src', 'img/bal01-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal01-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal01-2.jpg'); $('#mobileView2').attr('src', 'img/bal01-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal01.jpg'); $('#tabletView3').attr('srcset', 'img/bal01.jpg'); $('#mobileView3').attr('src', 'img/bal01.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal01'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#bal02').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal02-1.jpg'); $('#tabletView').attr('srcset', 'img/bal02-1.jpg'); $('#mobileView').attr('src', 'img/bal02-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal02-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal02-2.jpg'); $('#mobileView2').attr('src', 'img/bal02-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal02.jpg'); $('#tabletView3').attr('srcset', 'img/bal02.jpg'); $('#mobileView3').attr('src', 'img/bal02.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal02'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#bal03').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal03-1.jpg'); $('#tabletView').attr('srcset', 'img/bal03-1.jpg'); $('#mobileView').attr('src', 'img/bal03-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal03-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal03-2.jpg'); $('#mobileView2').attr('src', 'img/bal03-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal03.jpg'); $('#tabletView3').attr('srcset', 'img/bal03.jpg'); $('#mobileView3').attr('src', 'img/bal03.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal03'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#bal04').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal04-1.jpg'); $('#tabletView').attr('srcset', 'img/bal04-1.jpg'); $('#mobileView').attr('src', 'img/bal04-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal04-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal04-2.jpg'); $('#mobileView2').attr('src', 'img/bal04-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal04.jpg'); $('#tabletView3').attr('srcset', 'img/bal04.jpg'); $('#mobileView3').attr('src', 'img/bal04.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal04'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#bal05').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal05-1.jpg'); $('#tabletView').attr('srcset', 'img/bal05-1.jpg'); $('#mobileView').attr('src', 'img/bal05-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal05-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal05-2.jpg'); $('#mobileView2').attr('src', 'img/bal05-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal05.jpg'); $('#tabletView3').attr('srcset', 'img/bal05.jpg'); $('#mobileView3').attr('src', 'img/bal05.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal05'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#bal06').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal06-1.jpg'); $('#tabletView').attr('srcset', 'img/bal06-1.jpg'); $('#mobileView').attr('src', 'img/bal06-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal06-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal06-2.jpg'); $('#mobileView2').attr('src', 'img/bal06-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal06.jpg'); $('#tabletView3').attr('srcset', 'img/bal06.jpg'); $('#mobileView3').attr('src', 'img/bal06.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal06'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#bal07').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal07-1.jpg'); $('#tabletView').attr('srcset', 'img/bal07-1.jpg'); $('#mobileView').attr('src', 'img/bal07-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal07-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal07-2.jpg'); $('#mobileView2').attr('src', 'img/bal07-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal07.jpg'); $('#tabletView3').attr('srcset', 'img/bal07.jpg'); $('#mobileView3').attr('src', 'img/bal07.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal07'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#bal08').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal08-1.jpg'); $('#tabletView').attr('srcset', 'img/bal08-1.jpg'); $('#mobileView').attr('src', 'img/bal08-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal08-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal08-2.jpg'); $('#mobileView2').attr('src', 'img/bal08-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal08.jpg'); $('#tabletView3').attr('srcset', 'img/bal08.jpg'); $('#mobileView3').attr('src', 'img/bal08.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal08'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#bal09').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal09-1.jpg'); $('#tabletView').attr('srcset', 'img/bal09-1.jpg'); $('#mobileView').attr('src', 'img/bal09-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal09-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal09-2.jpg'); $('#mobileView2').attr('src', 'img/bal09-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal09.jpg'); $('#tabletView3').attr('srcset', 'img/bal09.jpg'); $('#mobileView3').attr('src', 'img/bal09.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal09'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#bal10').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal10-1.jpg'); $('#tabletView').attr('srcset', 'img/bal10-1.jpg'); $('#mobileView').attr('src', 'img/bal10-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal10-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal10-2.jpg'); $('#mobileView2').attr('src', 'img/bal10-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal10.jpg'); $('#tabletView3').attr('srcset', 'img/bal10.jpg'); $('#mobileView3').attr('src', 'img/bal10.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal10'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#bal11').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/bal11-1.jpg'); $('#tabletView').attr('srcset', 'img/bal11-1.jpg'); $('#mobileView').attr('src', 'img/bal11-1.jpg'); $('#desktopView2').attr('srcset', 'img/bal11-2.jpg'); $('#tabletView2').attr('srcset', 'img/bal11-2.jpg'); $('#mobileView2').attr('src', 'img/bal11-2.jpg'); $('#desktopView3').attr('srcset', 'img/bal11.jpg'); $('#tabletView3').attr('srcset', 'img/bal11.jpg'); $('#mobileView3').attr('src', 'img/bal11.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Baleta bal11'); $('.product-images-item-info-color').text('Colores: ');$('#selector1').click();});
	$('#430').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/430-1.jpg'); $('#tabletView').attr('srcset', 'img/430-1.jpg'); $('#mobileView').attr('src', 'img/430-1.jpg'); $('#desktopView2').attr('srcset', 'img/430-2.jpg'); $('#tabletView2').attr('srcset', 'img/430-2.jpg'); $('#mobileView2').attr('src', 'img/430-2.jpg'); $('#desktopView3').attr('srcset', 'img/430.jpg'); $('#tabletView3').attr('srcset', 'img/430.jpg'); $('#mobileView3').attr('src', 'img/430.jpg'); $('.product-images-item-info-material').text('Material:  Sintético'); $('.product-images-item-info-price').text('Bota 430NE'); $('.product-images-item-info-color').text('Colores: Tabaco, Negro, Beige, Café.');$('#selector1').click();});
	$('#1150').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/1150-1.jpg'); $('#tabletView').attr('srcset', 'img/1150-1.jpg'); $('#mobileView').attr('src', 'img/1150-1.jpg'); $('#desktopView2').attr('srcset', 'img/1150-2.jpg'); $('#tabletView2').attr('srcset', 'img/1150-2.jpg'); $('#mobileView2').attr('src', 'img/1150-2.jpg'); $('#desktopView3').attr('srcset', 'img/1150.jpg'); $('#tabletView3').attr('srcset', 'img/1150.jpg'); $('#mobileView3').attr('src', 'img/1150.jpg'); $('.product-images-item-info-material').text('Material:  Sintético'); $('.product-images-item-info-price').text('Bota 1150TAB'); $('.product-images-item-info-color').text('Colores: Café, Beige, Negro, Tabaco.');$('#selector1').click();});
	$('#0115').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/0115-1.jpg'); $('#tabletView').attr('srcset', 'img/0115-1.jpg'); $('#mobileView').attr('src', 'img/0115-1.jpg'); $('#desktopView2').attr('srcset', 'img/0115-2.jpg'); $('#tabletView2').attr('srcset', 'img/0115-2.jpg'); $('#mobileView2').attr('src', 'img/0115-2.jpg'); $('#desktopView3').attr('srcset', 'img/0115.jpg'); $('#tabletView3').attr('srcset', 'img/0115.jpg'); $('#mobileView3').attr('src', 'img/0115.jpg'); $('.product-images-item-info-material').text('Material:  Sintético'); $('.product-images-item-info-price').text('Bota 0115TAB'); $('.product-images-item-info-color').text('Colores: Tabaco, Negro, Beige, Café.');$('#selector1').click();});
	$('#extlar').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/extlar-1.jpg'); $('#tabletView').attr('srcset', 'img/extlar-1.jpg'); $('#mobileView').attr('src', 'img/extlar-1.jpg'); $('#desktopView2').attr('srcset', 'img/extlar-2.jpg'); $('#tabletView2').attr('srcset', 'img/extlar-2.jpg'); $('#mobileView2').attr('src', 'img/extlar-2.jpg'); $('#desktopView3').attr('srcset', 'img/extlar.jpg'); $('#tabletView3').attr('srcset', 'img/extlar.jpg'); $('#mobileView3').attr('src', 'img/extlar.jpg'); $('.product-images-item-info-material').text('Material:  Sintético'); $('.product-images-item-info-price').text('Bota extlarTAB'); $('.product-images-item-info-color').text('Colores: Café, Tabaco, Negro, Beige, Palorosa, Salmón, Rojo, Azul, Vinotinto, Verde.');$('#selector1').click();});
	$('#0121').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/0121-1.jpg'); $('#tabletView').attr('srcset', 'img/0121-1.jpg'); $('#mobileView').attr('src', 'img/0121-1.jpg'); $('#desktopView2').attr('srcset', 'img/0121-2.jpg'); $('#tabletView2').attr('srcset', 'img/0121-2.jpg'); $('#mobileView2').attr('src', 'img/0121-2.jpg'); $('#desktopView3').attr('srcset', 'img/0121.jpg'); $('#tabletView3').attr('srcset', 'img/0121.jpg'); $('#mobileView3').attr('src', 'img/0121.jpg'); $('.product-images-item-info-material').text('Material:  Sintético'); $('.product-images-item-info-price').text('Bota 0121NE'); $('.product-images-item-info-color').text('Colores: Negro, Tabaco, Beige, Miel.');$('#selector1').click();});
	$('#0124').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/0124-1.jpg'); $('#tabletView').attr('srcset', 'img/0124-1.jpg'); $('#mobileView').attr('src', 'img/0124-1.jpg'); $('#desktopView2').attr('srcset', 'img/0124-2.jpg'); $('#tabletView2').attr('srcset', 'img/0124-2.jpg'); $('#mobileView2').attr('src', 'img/0124-2.jpg'); $('#desktopView3').attr('srcset', 'img/0124.jpg'); $('#tabletView3').attr('srcset', 'img/0124.jpg'); $('#mobileView3').attr('src', 'img/0124.jpg'); $('.product-images-item-info-material').text('Material:  Sintético'); $('.product-images-item-info-price').text('Bota 0124NE'); $('.product-images-item-info-color').text('Colores: Negro, Tabaco, Beige, Miel.');$('#selector1').click();});
	$('#0127').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/0127-1.jpg'); $('#tabletView').attr('srcset', 'img/0127-1.jpg'); $('#mobileView').attr('src', 'img/0127-1.jpg'); $('#desktopView2').attr('srcset', 'img/0127-2.jpg'); $('#tabletView2').attr('srcset', 'img/0127-2.jpg'); $('#mobileView2').attr('src', 'img/0127-2.jpg'); $('#desktopView3').attr('srcset', 'img/0127.jpg'); $('#tabletView3').attr('srcset', 'img/0127.jpg'); $('#mobileView3').attr('src', 'img/0127.jpg'); $('.product-images-item-info-material').text('Material:  Sintético'); $('.product-images-item-info-price').text('Bota 0127NE'); $('.product-images-item-info-color').text('Colores: Tabaco, Negro, Beige, Café.');$('#selector1').click();});
	$('#201').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/201-1.jpg'); $('#tabletView').attr('srcset', 'img/201-1.jpg'); $('#mobileView').attr('src', 'img/201-1.jpg'); $('#desktopView2').attr('srcset', 'img/201-2.jpg'); $('#tabletView2').attr('srcset', 'img/201-2.jpg'); $('#mobileView2').attr('src', 'img/201-2.jpg'); $('#desktopView3').attr('srcset', 'img/201.jpg'); $('#tabletView3').attr('srcset', 'img/201.jpg'); $('#mobileView3').attr('src', 'img/201.jpg'); $('.product-images-item-info-material').text('Material: Charol'); $('.product-images-item-info-price').text('Casual 201RO'); $('.product-images-item-info-color').text('Colores: Café, Tabaco, Negro, Beige, Palorosa, Salmón, Rojo, Azul, Vinotinto, Verde.');$('#selector1').click();});
	$('#234').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/234-1.jpg'); $('#tabletView').attr('srcset', 'img/234-1.jpg'); $('#mobileView').attr('src', 'img/234-1.jpg'); $('#desktopView2').attr('srcset', 'img/234-2.jpg'); $('#tabletView2').attr('srcset', 'img/234-2.jpg'); $('#mobileView2').attr('src', 'img/234-2.jpg'); $('#desktopView3').attr('srcset', 'img/234.jpg'); $('#tabletView3').attr('srcset', 'img/234.jpg'); $('#mobileView3').attr('src', 'img/234.jpg'); $('.product-images-item-info-material').text('Material: Cuero Carnaza'); $('.product-images-item-info-price').text('Casual 234RO'); $('.product-images-item-info-color').text('Colores: Café, Tabaco, Negro, Beige, Palorosa, Salmón, Rojo, Azul, Vinotinto, Verde.');$('#selector1').click();});
	$('#0066').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/0066-1.jpg'); $('#tabletView').attr('srcset', 'img/0066-1.jpg'); $('#mobileView').attr('src', 'img/0066-1.jpg'); $('#desktopView2').attr('srcset', 'img/0066-2.jpg'); $('#tabletView2').attr('srcset', 'img/0066-2.jpg'); $('#mobileView2').attr('src', 'img/0066-2.jpg'); $('#desktopView3').attr('srcset', 'img/0066.jpg'); $('#tabletView3').attr('srcset', 'img/0066.jpg'); $('#mobileView3').attr('src', 'img/0066.jpg'); $('.product-images-item-info-material').text('Material: Cuero'); $('.product-images-item-info-price').text('Casual 0066CF'); $('.product-images-item-info-color').text('Colores: Café, Tabaco, Negro, Beige, Palorosa, Salmón, Rojo, Azul, Vinotinto, Verde.');$('#selector1').click();});
	$('#054').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/054-1.jpg'); $('#tabletView').attr('srcset', 'img/054-1.jpg'); $('#mobileView').attr('src', 'img/054-1.jpg'); $('#desktopView2').attr('srcset', 'img/054-2.jpg'); $('#tabletView2').attr('srcset', 'img/054-2.jpg'); $('#mobileView2').attr('src', 'img/054-2.jpg'); $('#desktopView3').attr('srcset', 'img/054.jpg'); $('#tabletView3').attr('srcset', 'img/054.jpg'); $('#mobileView3').attr('src', 'img/054.jpg'); $('.product-images-item-info-material').text('Material: Microfibra'); $('.product-images-item-info-price').text('Botín 054NE'); $('.product-images-item-info-color').text('Colores: Beige, Café, Negro, Azul, Rojo, Gris.');$('#selector1').click();});
	$('#055').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/055-1.jpg'); $('#tabletView').attr('srcset', 'img/055-1.jpg'); $('#mobileView').attr('src', 'img/055-1.jpg'); $('#desktopView2').attr('srcset', 'img/055-2.jpg'); $('#tabletView2').attr('srcset', 'img/055-2.jpg'); $('#mobileView2').attr('src', 'img/055-2.jpg'); $('#desktopView3').attr('srcset', 'img/055.jpg'); $('#tabletView3').attr('srcset', 'img/055.jpg'); $('#mobileView3').attr('src', 'img/055.jpg'); $('.product-images-item-info-material').text('Material: Microfibra'); $('.product-images-item-info-price').text('Botín 055NE'); $('.product-images-item-info-color').text('Colores: Beige, Café, Negro, Azul, Rojo, Gris.');$('#selector1').click();});
	$('#635').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/635-1.jpg'); $('#tabletView').attr('srcset', 'img/635-1.jpg'); $('#mobileView').attr('src', 'img/635-1.jpg'); $('#desktopView2').attr('srcset', 'img/635-2.jpg'); $('#tabletView2').attr('srcset', 'img/635-2.jpg'); $('#mobileView2').attr('src', 'img/635-2.jpg'); $('#desktopView3').attr('srcset', 'img/635.jpg'); $('#tabletView3').attr('srcset', 'img/635.jpg'); $('#mobileView3').attr('src', 'img/635.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Botín 635NE'); $('.product-images-item-info-color').text('Colores: Negro, Vinotinto, Tabaco, Beige, Café.');$('#selector1').click();});
	$('#727').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/727-1.jpg'); $('#tabletView').attr('srcset', 'img/727-1.jpg'); $('#mobileView').attr('src', 'img/727-1.jpg'); $('#desktopView2').attr('srcset', 'img/727-2.jpg'); $('#tabletView2').attr('srcset', 'img/727-2.jpg'); $('#mobileView2').attr('src', 'img/727-2.jpg'); $('#desktopView3').attr('srcset', 'img/727.jpg'); $('#tabletView3').attr('srcset', 'img/727.jpg'); $('#mobileView3').attr('src', 'img/727.jpg'); $('.product-images-item-info-material').text('Material: Montecarlo'); $('.product-images-item-info-price').text('Botín 727TAB'); $('.product-images-item-info-color').text('Colores: Café, Negro, Tabaco, Beige.');$('#selector1').click();});
	$('#269').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/269-1.jpg'); $('#tabletView').attr('srcset', 'img/269-1.jpg'); $('#mobileView').attr('src', 'img/269-1.jpg'); $('#desktopView2').attr('srcset', 'img/269-2.jpg'); $('#tabletView2').attr('srcset', 'img/269-2.jpg'); $('#mobileView2').attr('src', 'img/269-2.jpg'); $('#desktopView3').attr('srcset', 'img/269.jpg'); $('#tabletView3').attr('srcset', 'img/269.jpg'); $('#mobileView3').attr('src', 'img/269.jpg'); $('.product-images-item-info-material').text('Material: Cuero / Sintético'); $('.product-images-item-info-price').text('Botín 269MI'); $('.product-images-item-info-color').text('Colores: Beige, Tabaco, Café, Negro.');$('#selector1').click();});
	$('#618').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/618-1.jpg'); $('#tabletView').attr('srcset', 'img/618-1.jpg'); $('#mobileView').attr('src', 'img/618-1.jpg'); $('#desktopView2').attr('srcset', 'img/618-2.jpg'); $('#tabletView2').attr('srcset', 'img/618-2.jpg'); $('#mobileView2').attr('src', 'img/618-2.jpg'); $('#desktopView3').attr('srcset', 'img/618.jpg'); $('#tabletView3').attr('srcset', 'img/618.jpg'); $('#mobileView3').attr('src', 'img/618.jpg'); $('.product-images-item-info-material').text('Material: Montecarlo'); $('.product-images-item-info-price').text('Botín 618AL'); $('.product-images-item-info-color').text('Colores: Beige, Tabaco, Café, Negro.');$('#selector1').click();});
	$('#046').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/046-1.jpg'); $('#tabletView').attr('srcset', 'img/046-1.jpg'); $('#mobileView').attr('src', 'img/046-1.jpg'); $('#desktopView2').attr('srcset', 'img/046-2.jpg'); $('#tabletView2').attr('srcset', 'img/046-2.jpg'); $('#mobileView2').attr('src', 'img/046-2.jpg'); $('#desktopView3').attr('srcset', 'img/046.jpg'); $('#tabletView3').attr('srcset', 'img/046.jpg'); $('#mobileView3').attr('src', 'img/046.jpg'); $('.product-images-item-info-material').text('Material: Cuero'); $('.product-images-item-info-price').text('Botín 046VI'); $('.product-images-item-info-color').text('Colores: Café, Tabaco, Negro, Beige, Palorosa, Salmón, Rojo, Azul, Vinotinto, Verde.');$('#selector1').click();});
	$('#725').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/725-1.jpg'); $('#tabletView').attr('srcset', 'img/725-1.jpg'); $('#mobileView').attr('src', 'img/725-1.jpg'); $('#desktopView2').attr('srcset', 'img/725-2.jpg'); $('#tabletView2').attr('srcset', 'img/725-2.jpg'); $('#mobileView2').attr('src', 'img/725-2.jpg'); $('#desktopView3').attr('srcset', 'img/725.jpg'); $('#tabletView3').attr('srcset', 'img/725.jpg'); $('#mobileView3').attr('src', 'img/725.jpg'); $('.product-images-item-info-material').text('Material: Montecarlo'); $('.product-images-item-info-price').text('Botín 725TAB'); $('.product-images-item-info-color').text('Colores: Beige, Negro, Tabaco, Café.');$('#selector1').click();});
	$('#308').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/308-1.jpg'); $('#tabletView').attr('srcset', 'img/308-1.jpg'); $('#mobileView').attr('src', 'img/308-1.jpg'); $('#desktopView2').attr('srcset', 'img/308-2.jpg'); $('#tabletView2').attr('srcset', 'img/308-2.jpg'); $('#mobileView2').attr('src', 'img/308-2.jpg'); $('#desktopView3').attr('srcset', 'img/308.jpg'); $('#tabletView3').attr('srcset', 'img/308.jpg'); $('#mobileView3').attr('src', 'img/308.jpg'); $('.product-images-item-info-material').text('Material: Castor'); $('.product-images-item-info-price').text('Botín 308NE'); $('.product-images-item-info-color').text('Colores: Beige, Negro, Tabaco, Azul, Gris, Rojo');$('#selector1').click();});
	$('#305').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/305-1.jpg'); $('#tabletView').attr('srcset', 'img/305-1.jpg'); $('#mobileView').attr('src', 'img/305-1.jpg'); $('#desktopView2').attr('srcset', 'img/305-2.jpg'); $('#tabletView2').attr('srcset', 'img/305-2.jpg'); $('#mobileView2').attr('src', 'img/305-2.jpg'); $('#desktopView3').attr('srcset', 'img/305.jpg'); $('#tabletView3').attr('srcset', 'img/305.jpg'); $('#mobileView3').attr('src', 'img/305.jpg'); $('.product-images-item-info-material').text('Material: Castor'); $('.product-images-item-info-price').text('Botín 305NE'); $('.product-images-item-info-color').text('Colores: Beige, Negro, Tabaco, Azul, Gris, Rojo');$('#selector1').click();});
	$('#300').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/300-1.jpg'); $('#tabletView').attr('srcset', 'img/300-1.jpg'); $('#mobileView').attr('src', 'img/300-1.jpg'); $('#desktopView2').attr('srcset', 'img/300-2.jpg'); $('#tabletView2').attr('srcset', 'img/300-2.jpg'); $('#mobileView2').attr('src', 'img/300-2.jpg'); $('#desktopView3').attr('srcset', 'img/300.jpg'); $('#tabletView3').attr('srcset', 'img/300.jpg'); $('#mobileView3').attr('src', 'img/300.jpg'); $('.product-images-item-info-material').text('Material: Castor'); $('.product-images-item-info-price').text('Botín 300NE'); $('.product-images-item-info-color').text('Colores: Beige, Negro, Tabaco, Azul, Gris, Rojo');$('#selector1').click();});
	$('#635-3').click(function() {$('.product').css({display: 'block'}); $('.gallery').css({display: 'block'}); $('#desktopView').attr('srcset', 'img/635-4.jpg'); $('#tabletView').attr('srcset', 'img/635-4.jpg'); $('#mobileView').attr('src', 'img/635-4.jpg'); $('#desktopView2').attr('srcset', 'img/635-5.jpg'); $('#tabletView2').attr('srcset', 'img/635-5.jpg'); $('#mobileView2').attr('src', 'img/635-5.jpg'); $('#desktopView3').attr('srcset', 'img/635-3.jpg'); $('#tabletView3').attr('srcset', 'img/635-3.jpg'); $('#mobileView3').attr('src', 'img/635-3.jpg'); $('.product-images-item-info-material').text('Material: Sintético'); $('.product-images-item-info-price').text('Botín 635VI'); $('.product-images-item-info-color').text('Colores: Negro, Vinotinto, Tabaco, Beige, Café.');$('#selector1').click();});




}())